name: winslib
version: '${project.version}'
main: org.slavawins.winslib.Winslib
api-version: '1.20'
commands:
  winslibauthevent:
    description: Вызывается после авторизации, для связи с НЛОгНИ плагом /winslibauthevent login @player
    usage: <command>